env: development
app:
  port: 3000
database:
  type: 
  host: 
  port: 
  database: 
  user: 
  password: 
redis:
  host: 
  port: 6379
  password:
  ttl: 60
jwt:
  secret: secret
  expired: 36000000
  publicKey:
  algorithm: RS256
open-ai:
  api-key:
  project-id:
multer:
  destination: resumes
